"""Learn-mode logic: pick a reference page, derive rules, write ``conf.md``."""

from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable

from . import ui
from .analyzer import compute_gaps, group_into_rows
from .conf import write_conf
from .models import GapRule, Page, Report
from .reader import iter_pages, iter_visuals


def list_pages(report: Report) -> list[Page]:
    return list(iter_pages(report))


def prompt_page_selection(pages: list[Page]) -> Page | None:
    """Print a numbered list and prompt the user to pick one. ``None`` on cancel."""
    if not pages:
        ui.error("no pages found in report")
        return None
    print()
    ui.header("Pages in report:")
    for i, p in enumerate(pages, start=1):
        print(f"  {i}. {p.display_name}  ({p.id})")
    print()
    while True:
        try:
            answer = input("Pick a reference page (number, or 'q' to cancel): ").strip()
        except EOFError:
            return None
        if not answer or answer.lower() in ("q", "quit", "cancel"):
            return None
        try:
            idx = int(answer)
        except ValueError:
            ui.warn(f"not a number: {answer!r}")
            continue
        if 1 <= idx <= len(pages):
            return pages[idx - 1]
        ui.warn(f"out of range: pick 1..{len(pages)}")


def derive_rules(page: Page, visuals: Iterable[object]) -> tuple[list[GapRule], list[str]]:
    """Compute rules for one page. Returns (rules, conflict_warning_lines).

    Each (from_type, to_type) appears once. Conflicts are resolved by:
    most-frequent gap wins; ties → smallest gap. A warning line is recorded for
    every (from, to) pair that had >1 distinct gap on the page.
    """
    rows = group_into_rows(visuals)  # type: ignore[arg-type]
    pair_gaps: dict[tuple[str, str], list[int]] = defaultdict(list)
    for upper, lower, gap in compute_gaps(rows):
        pair = (upper.representative_type, lower.representative_type)
        pair_gaps[pair].append(int(round(gap)))

    rules: list[GapRule] = []
    warnings: list[str] = []
    for (from_t, to_t), gaps in pair_gaps.items():
        chosen = _pick_canonical_gap(gaps)
        rules.append(GapRule(from_type=from_t, to_type=to_t, gap_px=chosen))
        if len(set(gaps)) > 1:
            warnings.append(
                f"page '{page.display_name}' had conflicting gaps for "
                f"{from_t} -> {to_t}: saw {gaps}, chose {chosen} (most frequent, "
                f"ties → smallest)"
            )
    return rules, warnings


def _pick_canonical_gap(gaps: list[int]) -> int:
    counts = Counter(gaps)
    # Sort by (-count, gap) → most frequent; ties broken by smallest value.
    return sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]


def learn(
    report: Report,
    page: Page,
    out_path: Path,
    *,
    force: bool = False,
) -> Path | None:
    """Run the learn workflow. Returns the written path, or ``None`` on cancel."""
    if out_path.exists() and not force:
        if not ui.prompt_yes_no(f"Overwrite existing {out_path}?", default=False):
            ui.warn("aborted; existing file kept")
            return None

    visuals = list(iter_visuals(page))
    rules, warnings = derive_rules(page, visuals)

    if not rules:
        ui.error(
            f"page '{page.display_name}' yielded zero rules "
            "(needs at least 2 rows of visuals)"
        )
        return None

    header_lines = [
        "# PBIR Layout spacing rules",
        f"# Generated by pbir_validator from page: {page.display_name}",
        "# Format: <from_type> -> <to_type>: <gap>px",
        "# Edit by hand if needed; comments start with #.",
    ]
    for w in warnings:
        header_lines.append(f"# WARNING: {w}")
        ui.warn(w)

    write_conf(rules, out_path, header_lines=header_lines)
    ui.success(f"Wrote {len(rules)} rule(s) to {out_path}")
    return out_path
